language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
#  - clang

before_install:
- sudo apt-get update
- sudo apt-get install npm

install: npm install

script:
  - cmake ./
  - make
  - ./bin/amo_tools_suite_tests
  - npm run test
